[package]
name = "magick-cookie"
version = "0.1.0"
description = "Magick Cookie — personal productivity app"
authors = ["bumblelab"]
edition = "2021"

[lib]
name = "magick_cookie_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png", "unstable"] }
url = "2"
tauri-plugin-opener = "2"
tauri-plugin-notification = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["stream", "blocking"] }
futures-util = "0.3"
tokio = { version = "1", features = ["fs"] }
zip = "2"
hound = "3.5"
tauri-plugin-global-shortcut = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
uuid = { version = "1", features = ["v4"] }
portable-pty = "0.8"
notify = "7"
notify-debouncer-mini = "0.7"
keepass = { version = "0.8", features = ["save_kdbx4"] }
tauri-plugin-stronghold = "2"
xcap = "0.2"
base64 = "0.22"
dirs = "6.0.0"
chrono = { version = "0.4", features = ["serde"] }
zeroize = "1"
sha2 = "0.10"
flate2 = "1"
tar = "0.4"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
