services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: magick-cookie-mail
    hostname: mail.paltemps.fr
    domainname: paltemps.fr
    restart: unless-stopped
    ports:
      - "1025:25"    # SMTP
      - "1143:143"   # IMAP STARTTLS
      - "1587:587"   # Submission
      - "1993:993"   # IMAPS
    volumes:
      - mail-data:/var/mail
      - mail-state:/var/mail-state
      - mail-logs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    environment:
      - OVERRIDE_HOSTNAME=mail.paltemps.fr
      - PERMIT_DOCKER=network
      - SSL_TYPE=self-signed
      - ONE_DIR=1
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ENABLE_SASLAUTHD=0
      - POSTFIX_MESSAGE_SIZE_LIMIT=25000000
    cap_add:
      - NET_ADMIN

volumes:
  mail-data:
  mail-state:
  mail-logs:
